<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TwitchDropsBot.Core\TwitchDropsBot.Core.csproj" />
      <ProjectReference Include="..\TwitchDropsBot.Web\TwitchDropsBot.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.0" />
      <PackageReference Include="QRCoder" Version="1.8.0" />
      <PackageReference Include="System.CommandLine" Version="2.0.0" />
    </ItemGroup>

</Project>
